name: Cancel Stale Waiting Rounds

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:  

jobs:
  call-function:
    runs-on: ubuntu-latest
    steps:
      - name: Call Supabase Function
        run: |
          curl -X POST "https://anqntfmpvheyuiquqmui.supabase.co/functions/v1/game-management/cancel-stale-waiting-rounds" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}"